/* eslint-disable @typescript-eslint/no-misused-promises */
import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton,useUser  } from "@clerk/nextjs";
import { useClerk } from "@clerk/clerk-react";

const Home: NextPage = () => {

  const { isSignedIn } = useUser();
  const { signOut } = useClerk();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">

          {isSignedIn ?  <button onClick={() => signOut()} >
      Sign out
    </button> : <SignInButton>Sign in</SignInButton>   }
          
      </main>
    </>
  );
};

export default Home;
